# Generated by Django 6.1.1 on 2026-09-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_products_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='listPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='list_prod')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='products.products')),
            ],
        ),
    ]
