# Generated by Django 6.1.1 on 2026-09-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='categories.categories'),
        ),
    ]
