# Generated by Django 6.1.1 on 2026-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='article',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
